name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./src --file src/Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/mmacardsapi:${{ steps.semver.outputs.next }} --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/mmacardsapi:latest

    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - uses: actions/checkout@v3
    - name: Push the docker image
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mmacardsapi:latest
