name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get next version
      uses: reecetech/version-increment@2023.4.1
      id: version
      with:
        scheme: semver
        increment: patch
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./src --file src/Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/mmacardsapi:${{ steps.version.outputs.version }} --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/mmacardsapi:latest

    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - uses: actions/checkout@v3
    - name: Push the docker image
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mmacardsapi:latest
