name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Bump version
      uses: copapow/version-bump-package@v1
      with:
        default_branch: main
        github_token: ${{secrets.GITHUB_TOKEN}}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/mmacardsapi:${{ steps.bump_version.outputs.new_version }} --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/mmacardsapi:latest

    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - uses: actions/checkout@v3
    - name: Push the docker image
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mmacardsapi:latest
